cache: bundler

language: ruby
rvm:
  - 1.9.3
  - 2.2.2
before_install:
  - rm .rvmrc
before_script:
  - bundle exec rake app:db:schema:load
script:
  - "xvfb-run bundle exec rspec spec/"

sudo: false
gemfile:
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.2.gemfile